"""initial_migration

Revision ID: 45f9387936db
Revises: 
Create Date: 2025-01-15 12:49:28.442036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f9387936db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('ean', sa.String(length=13), nullable=False),
    sa.Column('price', sa.Numeric(precision=25, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('local', sa.Enum('event', 'store', name='localenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ean')
    )
    op.create_index(op.f('ix_tb_products_id'), 'tb_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_products_id'), table_name='tb_products')
    op.drop_table('tb_products')
    # ### end Alembic commands ###
