version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - app-network

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./localstack:/var/lib/localstack"
      - "./s3-config:/etc/localstack/init/ready.d/"
    networks:
      - app-network

  python-app:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: python_app_container
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - localstack
    networks:
      - app-network
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      S3_ENDPOINT: ${S3_ENDPOINT}
      NETWORK_S3_ENDPOINT: ${NETWORK_S3_ENDPOINT}

  react-app:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: react_app_container
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      REACT_APP_BACK_END_URL: ${REACT_APP_BACK_END_URL}
    depends_on:
      - python-app

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
